### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by huangchieh** [huangchieh/StructureMetrics#1]
- [x] Add basic code to calculate the distribution P.  
- [ ] Calculate Q distributions after obtain all structures. For images not from experiment. 
- [ ] Add functions to calculate KL divergence.
